Adding Hydraulic Pneumatic Friction plugin
osrf/buoy_sim pull request #100
Opened 2022-10-11 05:15 UTC by quarkytale

A new plugin and test framework is ready. Need to work on model accuracy.

2022-10-12 05:00 UTC, hamilton8415 commented
Nice job Dharini making a clean and simple plugin to address this need.  I have a few suggestions for checking/consideration.   The friction force versus speed interpolation defined by:

 pistonSpeed{-0.4F, -0.3F, -0.2F, -0.1F, 0.0F, 0.1F, 0.2F, 0.3F, 0.4F},
 meanFriction{1200.0F, 1000.0F, 700.0F, 500.0F, 0.0F, -1000.0F, -1400.0F, -2100.0F, -2900.0F} 

probably needs a larger extend, in the paper tests were done up to these speeds (+/- 0.4 m/s) but in actuality the piston could go quite a bit faster.  I'd say to be sure of covering the possibilities, the chart should go up to +/- 2m/s.  Because this interpolation consists of just a few straight lines, it may not be necessary to include points in the intermediate parts of the straight sections, which could speed up the interpolation some.  I  believe splinter may be configured to use the highest values in the interpolation table when independent variables greater than the defined extent are used, this would be good to include if it's possible.  @andermi knows what's possible I believe.

Also, in what's sure to be a continual source of confusion, the internal gazebo model uses and opposite sign for the position of the ram extension compared with the paper and actual system at sea.  So we need to swap the sign of the velocity relative to the paper.  For now I suggest we keep this annoyance as we've addressed it throughout the code in a number of places, if we decide to change it to match, we can do it once and hopefully find all places to fix it.

Finally, I will suggest a simpler name for this plugin.  I think PTO_Friction or similar is fine, the friction being simulated here is a combination of a lot of contributions, from the hydraulic ram, from the pneumatic part, from extraneous other seals, etc.  So avoiding the specificity of HydraulicPneumatic might be a good idea.  Not too important if it's challenging to change.

2022-10-13 16:49 UTC, quarkytale commented
That's exactly the feedback I was looking for, thanks Andy! 
I saw the behaviour with speed outside the bounds I modelled for was kinda weird. I would want to add all the values inclusive of the range speed will touch. Love some help on getting that data. Otherwise, I'm not sure how to configure the splinter to work that case, will ping Michael!
Changes upcoming:
- Switching the speed's sign
- Changing plugin name to PTOFriction

2022-10-13 17:27 UTC, hamilton8415 commented
Michael is out on the boat today, so here's an example of splinter use from elsewhere that returns the endpoints when an out of bound request is made:
 const double eff_m = this->hyd_eff_m.eval(rpm, splinter_ros::USE_BOUNDS);  

I haven't tested this carefully, (in michael we trust...:), but in the friction case we'd still want a wide expanse and only count on this for the unexpected case of a higher speed than expected.  Otherwise I'm not sure what spinter returns when the argument is out of bounds, perhaps it extrapolates, or returns dragons...

2022-10-15 03:18 UTC, quarkytale commented
Update the plugin as per feedback. 
The model is still very inaccurate:
```
/home/osrf/buoy_ws/src/buoy_sim/buoy_gazebo/test/test_pto_friction.cpp:41: Failure
2: The difference between 0.0 and friction_model.eval(0.0, splinter_ros::USE_BOUNDS) is 150.00000000000006, which exceeds 0.05, where
2: 0.0 evaluates to 0,
2: friction_model.eval(0.0, splinter_ros::USE_BOUNDS) evaluates to -150.00000000000006, and
2: 0.05 evaluates to 0.050000000000000003.
2: /home/osrf/buoy_ws/src/buoy_sim/buoy_gazebo/test/test_pto_friction.cpp:42: Failure
2: The difference between -2100.0 and friction_model.eval(-0.3, splinter_ros::USE_BOUNDS) is 193.74997289851353, which exceeds 100.0, where
2: -2100.0 evaluates to -2100,
2: friction_model.eval(-0.3, splinter_ros::USE_BOUNDS) evaluates to -2293.7499728985135, and
2: 100.0 evaluates to 100.
```
What's our tolerance?

2022-10-19 18:04 UTC, andermi commented on buoy_gazebo/src/PTOFriction/PTOFriction.cpp
> +    meanFriction{1200.0F, 700.0F, -1000.0F, -2900.0F},
if the vector is type `double`, omit the `F` to initialize with `double` literals rather than `float` literals

2022-10-19 18:08 UTC, andermi commented
> The model is still very inaccurate:

I'm going to open a PR in a moment to add a different interpolator. We have found issues with splinter not doing the right thing, unfortunately.

2022-10-19 18:54 UTC, andermi commented on buoy_gazebo/src/PTOFriction/PTOFriction.cpp
> +    meanFriction{1200.0F, 700.0F, -1000.0F, -2900.0F},
Also, I think the sign of the piston speed is flipped:

```
  : pistonSpeed{-0.4F, -0.1F, 0.1F, 0.4F},
    meanFriction{1200.0F, 700.0F, -1000.0F, -2900.0F},
```

2022-10-19 19:07 UTC, andermi commented on buoy_gazebo/src/PTOFriction/PTOFriction.cpp
> +    meanFriction{1200.0F, 700.0F, -1000.0F, -2900.0F},
it looks like a couple points could be added:

(-0.05, 400)  // endpoint of the left line
(0.0, 0.0)  // we'd like the applied force to be zero when the piston isn't in motion
(0.05, -750)  // starting point of the right line

2022-10-19 19:18 UTC, andermi commented on buoy_gazebo/src/PTOFriction/PTOFriction.cpp
> +    fabs(prismaticJointVelComp->Data().at(0)), this->dataPtr->fill_mode);
Since you have both negative speed and positive speed in your interpolation table (since they are different lines), don't take `fabs` here. Also, instead of flipping the sign in the table to account for the `x` direction difference between the sim and physical buoy, negate the velocity here.

```
-prismaticJointVelComp->Data().at(0)
```

2022-10-19 19:25 UTC, andermi commented on buoy_gazebo/src/PTOFriction/PTOFriction.cpp
> +    meanFriction{1200.0F, 700.0F, -1000.0F, -2900.0F},
also, extrapolating out to +/- 5 m/s as Andy suggests, I compute the following points:

(-5.0, 12750)
(5.0, 32033)

2022-10-31 21:26 UTC, mjcarroll commented
Pending removing splinter.

2022-11-07 22:38 UTC, mjcarroll commented
https://github.com/osrf/buoy_msgs/pull/36 has been merged, so you should be able to update accordingly here.

2022-11-08 20:28 UTC, andermi approved these changes
LGTM once splinter is replaced :+1:

2022-11-09 06:59 UTC, quarkytale commented
Replaced splinter, but the build will totally fail without the motor mode PR.

2022-11-09 20:55 UTC, andermi commented
> build will totally fail without the motor mode PR

Sorry, I didn't quite think that one through. The issue is that `ElectroHydraulicPTO` plugin still needs `splinter_ros`? ... and we can't remove the `splinter_ros` dependency without the switch to 1d interpolation on mechanical and volumetric efficiencies from motormode

2022-11-10 03:36 UTC, hamilton8415 commented
Agreed, I am running down a couple of test issues with motormode but let's aim to get that merged this week so we can have a buildable main again.

2022-11-22 18:37 UTC, quarkytale commented
buoy sc tests are failing since buoy position is now different with the friction added, working on updating the numbers.

2022-11-28 19:20 UTC, andermi requested changes
I just caught a couple more things

2022-11-28 19:20 UTC, andermi commented on buoy_gazebo/CMakeLists.txt
> +  gz_add_gtest(test_pto_friction ROS)
Please, move the test from `buoy_gazebo` to `buoy_tests`.

2022-11-28 19:20 UTC, andermi commented on buoy_gazebo/CMakeLists.txt
> +      set(ROS_PKGS rclcpp simple_interp ${gz_add_test_EXTRA_ROS_PKGS})
`simple_interp` should be added as an argument to the `gz_add_gtest` function after `EXTRA_ROS_PKGS` instead of explicitly adding it here.

2022-11-28 19:20 UTC, andermi commented on buoy_gazebo/CMakeLists.txt
> +  gz_add_gtest(test_pto_friction ROS)
use all of this in `buoy_tests` instead

2022-11-28 19:20 UTC, andermi commented on buoy_gazebo/CMakeLists.txt
> +      set(ROS_PKGS rclcpp simple_interp ${gz_add_test_EXTRA_ROS_PKGS})
In order to use your include files for the friction plugin in the test in `buoy_tests`, copy the pattern [here](https://github.com/osrf/buoy_sim/blob/55dcc0c0ce1728034a49cdacb3d711ab9dbdda2a/buoy_gazebo/CMakeLists.txt#L125-L128) to install your include files

2022-11-28 19:20 UTC, andermi commented on buoy_gazebo/test/test_pto_friction.cpp
> +};
Try including your plugin class rather than recreate here so we test the values in used in the plugin.

2022-11-28 19:20 UTC, andermi commented on buoy_gazebo/test/test_pto_friction.cpp
> +// Copyright 2020 Open Source Robotics Foundation, Inc.
move this whole test file to `buoy_tests`

2022-11-28 19:20 UTC, andermi commented on buoy_gazebo/test/test_pto_friction.cpp
> +TEST_F(PTOFrictionTest, ModelAccuracy)
This is a good test for the interpolator.
I wonder if it would be good to add a test like:

1. run the sim without the friction plugin disabled and measure settling time
2. run the sim with the friction plugin enabled and the settling time should be faster

2022-11-28 20:48 UTC, andermi commented on buoy_gazebo/CMakeLists.txt
> +      set(ROS_PKGS rclcpp simple_interp ${gz_add_test_EXTRA_ROS_PKGS})
Sorry, I was wrong about copying that pattern to use the includes. (I wasn't thinking quite clearly!)

You need to export the friction plugin library

2022-11-28 20:50 UTC, andermi commented on buoy_gazebo/CMakeLists.txt
> +      set(ROS_PKGS rclcpp simple_interp ${gz_add_test_EXTRA_ROS_PKGS})
but that's only if you want to use the class directly to recreate the test you made...
Or, you could just use the gz_sim test fixture and load the plugin that way for other testing

2022-11-30 00:53 UTC, quarkytale commented
Changing absement values is not affecting the piston motion

2022-11-30 01:16 UTC, andermi commented
> Changing absement values is not affecting the piston motion

fixed with 1ebd6c6

2022-12-05 19:15 UTC, andermi approved these changes
LGTM

2022-12-05 19:30 UTC, merged