Adding buoyancy
osrf/buoy_sim pull request #33
Opened 2022-05-05 06:27 UTC by quarkytale

To run `ign gazebo mbari_wec.sdf`

2022-05-05 18:50 UTC, chapulina reviewed
Just some quick feedback

2022-05-05 18:50 UTC, chapulina commented on buoy_description/models/mbari_wec/model.sdf.em
> +          </mesh>
Using this mesh to get the volume, it's being automatically calculated to almost 8 m^3:

![image](https://user-images.githubusercontent.com/5751272/166984758-438f37bd-68c9-4502-999a-bef45e8aa1ab.png)

According to @andermi on Slack, that should be closer to 0.1928 m^3.

I think it's best that we approximate the collision using a box whose dimensions result in the desired volume.

2022-05-05 22:38 UTC, andermi commented on buoy_description/models/mbari_wec/model.sdf.em
> +          </mesh>
do you need collision meshes for all links?

2022-05-05 22:45 UTC, quarkytale commented on buoy_description/models/mbari_wec/model.sdf.em
> +          </mesh>
Added a collision box of size `0.578 0.578 0.5771` which makes the volume to `0.1928 m^3`

2022-05-06 01:44 UTC, quarkytale commented on buoy_description/models/mbari_wec/model.sdf.em
> +          </mesh>
@andermi I'm guessing collision meshes for all links would be good in the long run. I have a question though from `pto_collision.stl` the volume is coming to `0.161425` but in the Slack thread it was supposed to come out to `0.3139 m^3`. Should I use an approximate box too for the PTO or the mesh is more accurate?

2022-05-06 18:13 UTC, chapulina commented on buoy_description/models/mbari_wec/model.sdf.em
> +          </mesh>
The collisions are having 2 separate roles at the moment:

* Actually work as collisions that bump into each other
* Defining the volume that's used by the buoyancy plugin

That duality may become cumbersome for links like the PTO, which need both properties, with different shapes.

Possible solutions:

1. Quickest: 
    * Leave PTO buoyancy coming from the STL for now
1. Almost as quick: 
    * Use proper STL meshes for what needs to collide, and boxes for buoyancy
    * The PTO would have 2 collisons with different roles
    * Exclude the PTO STL collision from the buoyancy plugin using the `<enable>` tag to explicitly enable all other collisions
    * Make sure the PTO's buoyancy collision can't physically collide with the tether
1. Best
    * Improve the buoyancy plugin with the suggestions in https://github.com/osrf/buoy_sim/issues/16#issuecomment-1115403060

I think we could start with `1.` on this PR and work on `3.` next.

2022-05-06 18:31 UTC, chapulina requested changes
The heave cone collision looks good to me. I have comments on the others.

2022-05-06 18:31 UTC, chapulina commented on buoy_description/models/mbari_wec/model.sdf.em
> +        <pose>0 0 -3.04 0 0 0 </pose>
We shouldn't move this collision, it's actually being used as a collision so we keep the tether in place. This is what it looks like with this PR:

![image](https://user-images.githubusercontent.com/5751272/167195573-c850852c-2f6a-413c-ac59-5aed9f0d6c82.png)

2022-05-06 18:31 UTC, chapulina commented on buoy_description/models/mbari_wec/model.sdf.em
> +        <pose>0 0 2.16 0 0 0 </pose>
This one too, if we're using the STL mesh, it can't have an offset:

![image](https://user-images.githubusercontent.com/5751272/167195978-328190df-8d5d-405c-86ca-bf507809e478.png)

2022-05-06 18:31 UTC, chapulina commented on buoy_description/models/mbari_wec/model.sdf.em
> +            <uri>meshes/buoy_float.stl</uri>
tl;dr: we should use a box here

The automatically calculated volume for this mesh is 17.0038 m^3.

The spec sheet says the water plane area is 5.47 m^2. If we consider 17 m^3 to be the correct submergible volume, that would mean that the buoy has > 3 m of submergible height, which seems too much for me. That's my way of saying that I think 17 is too high.

But even if 17 were the correct volume, an STL mesh wouldn't work well when we add a water plane using `<graded_buoyancy>`. So we need to use a box collision.

The dimensions of the box collision should be such that `dX * dY == 5.47` (the water plane area). I'm not sure about the height though. Do we know the submerged volume of the buoy at rest, @andermi ? We should be able to calculate `dZ` with that.

2022-05-06 18:57 UTC, chapulina commented
Another thing I should have mentioned before is that the ultimate test for the buoyancy should be to remove the joint that's currently preventing the model from sinking.

The buoyancy added in this PR should be tuned so that when the joint is removed:

* the model doesn't sink - if it does, we'll need to add more collisions or increase the ones we have
* the model doesn't fly away - we'll need the `graded_buoyancy` for that, so the buoy stops floating when it reaches the plane between the water and the air.

Judging by past experience, getting to the right balance may be very tricky and we may need to iterate on it every time something changes in the model. Let's see how the first pass goes and adjust as we go.

2022-05-10 23:23 UTC, quarkytale commented on buoy_description/models/mbari_wec/model.sdf.em
> +            <uri>meshes/buoy_float.stl</uri>
Not sure how much of the buoy should be covered for collision.
When I aimed for a volume of 5.47 (given 1m height), it just covers slightly more than half. Note the pose had to shifted too, the sheet had center of volume to be `0 0 2.16`.
![half_collision_buoy](https://user-images.githubusercontent.com/24695820/167740279-221ab33c-8efb-4215-b564-b76a931b5c58.png)

And this is the params with a box fully covering it.
![full_collision_buoy](https://user-images.githubusercontent.com/24695820/167740395-e96dde42-eb72-4843-90ee-9f260e6bbd78.png)

How should I proceed?

2022-05-10 23:24 UTC, quarkytale commented
Sneak peek of buoy submerged :)
![water_plane](https://user-images.githubusercontent.com/24695820/167740517-49099ed5-a99f-4136-bed7-a28dd46bb2d1.png)

2022-05-10 23:55 UTC, chapulina commented on buoy_description/models/mbari_wec/model.sdf.em
> +            <uri>meshes/buoy_float.stl</uri>
Let's go with the one on the top, the collision with only 1m height. That should match the displace water volume better.

2022-05-11 18:32 UTC, chapulina commented on buoy_description/models/mbari_wec/model.sdf.em
> +            <uri>meshes/buoy_float.stl</uri>
> Note the pose had to shifted too, the sheet had center of volume to be 0 0 2.16.

Ah I had missed that before. The current position looks good to me, because we're just approximating the actual volume at the moment. I think we can get this first iteration in with some offset and adjust as we add other forces.

2022-05-11 18:34 UTC, chapulina approved these changes
Great to see the joint to the world gone! And nice touch with the water plane 💯 

I shook the buoy a bit and it seems to be moving reasonably! No longer constrained to a single axis 😄 

![buoy_buoy](https://user-images.githubusercontent.com/5751272/167921349-e9ac2b37-672a-4885-839a-015dc339a5d1.gif)

2022-05-11 18:35 UTC, merged