Framework to View the buoy on RViz
osrf/buoy_sim pull request #50
Opened 2022-05-25 03:07 UTC by quarkytale

2022-06-03 04:16 UTC, chapulina commented
I'm able to load the meshes prefixed by `package://` on both RViz and Gazebo with this change:

```diff
diff --git a/buoy_description/hooks/buoy_description.dsv.in b/buoy_description/hooks/buoy_description.dsv.in
index 54beeea..c0ae662 100644
--- a/buoy_description/hooks/buoy_description.dsv.in
+++ b/buoy_description/hooks/buoy_description.dsv.in
@@ -1 +1 @@
-prepend-non-duplicate;IGN_GAZEBO_RESOURCE_PATH;share/@PROJECT_NAME@/models
+prepend-non-duplicate;IGN_GAZEBO_RESOURCE_PATH;share
```

What Gazebo does is strip everything up to `://` and try prefixing the rest of the URL with all paths in the `IGN_GAZEBO_RESOURCE_PATH` environment variable.

For example, with that change, after sourcing my colcon workspace, I see these values for the environment variable:

```
$ env | grep RES
IGN_GAZEBO_RESOURCE_PATH=/home/chapulina/dev_focal/ws_fortress/install/share/buoy_gazebo/worlds:/home/chapulina/dev_focal/ws_fortress/install/share
```

So consider a URI like this:

https://github.com/osrf/buoy_sim/blob/ff2f498a5afda06bf0a42d4188fc3d7bf6c582b4/buoy_gazebo/worlds/test_mbari_wec_model.sdf#L22

Gazebo will try:

1. `/home/chapulina/dev_focal/ws_fortress/install/share/buoy_gazebo/worlds/buoy_description/models/mbari_wec/meshes/buoy_float.stl` - that doesn't exist, continue
2. `/home/chapulina/dev_focal/ws_fortress/install/share/buoy_description/models/mbari_wec/meshes/buoy_float.stl` - that exists!

2022-06-03 04:53 UTC, chapulina reviewed
Just gave it a quick try

2022-06-03 04:53 UTC, chapulina commented on buoy_gazebo/launch/rviz.launch.py
> +        # Launch rviz
Not sure if that's already your plan, but to reduce duplication, it would be nice to make RViz an option of the `mbari_wec.launch.py` file. This way we keep using a single entry-point, and users can choose at runtime whether to launch RViz or not.

See an example here, note the `condition` on the RViz node and the `DeclareLaunchArgument`:

https://github.com/gazebosim/ros_gz/blob/galactic/ros_ign_gazebo_demos/launch/diff_drive.launch.py

2022-06-03 05:40 UTC, quarkytale commented on buoy_gazebo/launch/rviz.launch.py
> +        # Launch rviz
That was my plan but wasn't sure on how to implement it, thanks for the example!

2022-06-06 19:28 UTC, chapulina commented on buoy_gazebo/launch/mbari_wec.launch.py
> +            '/world/empty/model/test_mbari_wec_model/joint_state@sensor_msgs/msg/JointState[ignition.msgs.Model',
Now that you're loading `mbari_wec`, I think you need to update these topics

2022-06-06 19:28 UTC, chapulina commented on buoy_gazebo/worlds/test_mbari_wec_model.sdf
> +<?xml version="1.0" ?>
I think this world file isn't needed anymore, right? Then it can be removed

2022-06-06 19:28 UTC, chapulina commented on buoy_gazebo/launch/mbari_wec.launch.py
> +        executable='create',
Is this node needed? This is supposed to spawn the model into simulation, but the model is already hardcoded into the `mbari_wec.sdf` world file.

2022-06-06 19:28 UTC, chapulina commented on buoy_description/models/mbari_wec/model.sdf.em
> +<sdf version="1.7">
I think we should be able to keep 1.8 once we start using Fortress in `sdformat_urdf`, see

* https://github.com/ros/sdformat_urdf/pull/8

2022-06-07 23:19 UTC, quarkytale commented on buoy_gazebo/launch/mbari_wec.launch.py
> +        executable='create',
Its only required for testing with an empty world

2022-06-07 23:44 UTC, quarkytale commented
Though the functionality is still incomplete (tfs aren't being published, wip on ros_ign), this should be clear now to be merged as its won't affect simulating using gazebo!

2022-06-08 02:47 UTC, chapulina reviewed
Just checking, with this PR as is, the buoy doesn't show on RViz, right? We need TF for it?

Also note that there are linter errors.

2022-06-08 02:47 UTC, chapulina commented on buoy_description/models/mbari_wec/model.sdf.em
> +    </plugin>
Can we add this to the model in `mbari_wec.sdf`? It would be nice for the model to be plugin-free here, and each world file adds the plugins it needs.

2022-06-08 02:47 UTC, chapulina commented on buoy_gazebo/launch/mbari_wec.launch.py
> +            '/world/mbari_wec/model/mbari_wec/joint_state@sensor_msgs/msg/JointState[ignition.msgs.Model',
I suggest parametrizing the world and model name on these topics, so it's easier to update these topics in the future.

2022-06-08 02:47 UTC, chapulina commented on buoy_gazebo/launch/mbari_wec.launch.py
> +            {'use_sim_time': False},
Since we're using simulation, I believe this should be true

2022-06-08 07:51 UTC, quarkytale commented
> Just checking, with this PR as is, the buoy doesn't show on RViz, right? We need TF for it?
No the buoy would still be visible, only it can't translate movement in rviz as seen in gazebo.

I think I found the issue with the transforms. Seems like coming from here or its `ros2` equivalent https://github.com/ros/kdl_parser/blob/a1ba6dfffc9c95b30d8a099f8785db4cf5c0342f/kdl_parser/src/kdl_parser.cpp#L103. Not sure what this library does but missing universal joint support.

2022-06-14 00:14 UTC, chapulina requested changes
Great work! I just have some smaller comments, and we should wait for https://github.com/ros/sdformat_urdf/pull/13 to be merged before merging this one.

2022-06-14 00:14 UTC, chapulina commented on buoy_gazebo/rviz/mbari_wec.rviz
> +Panels:
I recommend removing the Views panel on the right, because it takes up space and isn't really necessary.

I also think it would be nice to have the config open with the whole buoy in view.

2022-06-14 00:14 UTC, chapulina commented on buoy_gazebo/launch/mbari_wec.launch.py
> +    world_name = 'playground'
How about defaulting to `mbari_wec` and exposing the world file as a launch argument?

2022-06-20 20:38 UTC, quarkytale commented
Support from `sdformat_urdf` and upstream Gazebo is all merged! This is ready for a final review.

2022-06-21 03:07 UTC, chapulina reviewed
LGTM! The only things missing before merging:

* See https://github.com/osrf/buoy_sim/pull/64 for handling the `tf_static` transform better
* We need an `ign-gazebo6` release with the changes from https://github.com/gazebosim/gz-sim/pull/1534, I'm working on it

2022-07-06 22:26 UTC, chapulina approved these changes
Works great! All necessary releases are out, this is good to go!

2022-07-06 22:26 UTC, merged